title : Test Drive
author: Frey
copyright: '2024'
logo: 'images/hpe-logo.png'

description: >-
  Test Drive Lab Guide

execute:
  execute_notebooks           : off

html:
  home_page_in_navbar         : true
  favicon                     : 'images/fav-icon-32.png'